import { ApolloWrapper } from "@/lib/apollo-wrapper";
// import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar">
      <body>
      <h1>Root layout</h1>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
